// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import plugin "github.com/nori-io/nori-common/plugin"

// Installable is an autogenerated mock type for the Installable type
type Installable struct {
	mock.Mock
}

// Install provides a mock function with given fields: ctx, registry
func (_m *Installable) Install(ctx context.Context, registry plugin.Registry) error {
	ret := _m.Called(ctx, registry)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, plugin.Registry) error); ok {
		r0 = rf(ctx, registry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnInstall provides a mock function with given fields: ctx, registry
func (_m *Installable) UnInstall(ctx context.Context, registry plugin.Registry) error {
	ret := _m.Called(ctx, registry)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, plugin.Registry) error); ok {
		r0 = rf(ctx, registry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
